[tool.poetry]
name = "queuery-client"
version = "1.1.0"
description = "Queuery Redshift HTTP API Client for Python"
authors = ["altescy <yasuhiro-yamaguchi@cookpad.com>", "himkt <himkt@cookpad.com>", "fufufukakaka <yusuke-fukasawa@cookpad.com>"]
readme = "README.md"
license = "MIT License"
homepage="https://github.com/bricolages/queuery_client_python"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = ">=2.25.0,<3.0.0"
python-dateutil = ">=2.8.0,<3.0.0"
pandas = {version = ">=1.2.0,<3.0.0", optional = true}
numpy = [
  {version = ">=1.26.4,<2.0", python = ">=3.9", optional = true},
  {version = "*", python = "=3.8", optional = true},
]

[tool.poetry.group.dev.dependencies]
python-language-server = "^0.36.2"
pytest = "^7.3.1"
pysen = "^0.11.0"
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^5.0.4"
mypy = "^1.13.0"
types-requests = "^2.31.0.10"
types-python-dateutil = "^2.8.19.14"

[tool.poetry.extras]
pandas = ["pandas", "numpy"]
all = ["pandas", "numpy"]

[tool.pysen]
version = "0.11"

[tool.pysen-cli]
settings_dir = "."

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 115
py_version = "py38"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]

[tool.pysen.lint.source]
  includes = ["."]
  excludes = [".venv/"]

[tool.black] # automatically generated by pysen
# pysen ignores and overwrites any modifications
line-length = 115
target-version = ["py38"]

[tool.isort] # automatically generated by pysen
# pysen ignores and overwrites any modifications
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
line_length = 115
multi_line_output = 3
use_parentheses = true
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
